<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Runner</AssemblyName>
    <RootNamespace>TriCoreDb.Conformance</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TriCoreDb\TriCoreDb.csproj" />
  </ItemGroup>

</Project>
